version: '3.1'

services:

  db:
    image: postgres
    restart: always
    env_file:
      - .env

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
        context: frontend
        dockerfile: Dockerfile
    restart: always
    volumes:
     - ./frontend:/usr/src/app
    ports:
     - 3000:3000
