# Generated by Django 4.1 on 2023-05-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='user/avatars/default_avatar.png', null=True, upload_to='user/avatars'),
        ),
    ]
