import type { NextPage } from 'next'
import Head from 'next/head'

import Header from '../components/Header/Header';
import UserMiniTitle from '../components/UserMiniTitle/UserMiniTitle'


const Home: NextPage = () => {
  return (
    <div>
      {/*
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      */}
      <Header></Header>
      <UserMiniTitle />
      <main>
        test
      </main>
        
    </div>
  )
}

export default Home
