# Generated by Django 4.1 on 2023-04-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relationships',
        ),
    ]
