# Generated by Django 4.1 on 2023-05-29 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relations_api', '0002_delete_relationships'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'verbose_name': 'FriendRequest', 'verbose_name_plural': 'FriendRequests'},
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='recipient',
            field=models.ForeignKey(help_text='User who receives friend request', on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='sender',
            field=models.ForeignKey(help_text='User who send friend request', on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
