# Generated by Django 4.1 on 2023-05-29 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='users_in_chat',
            field=models.ManyToManyField(related_name='users_in_chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
